plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.12.2'
}

javafx {
    version = '25'
    modules = ['javafx.controls']
}

application {
    mainClass = 'vermithor.Launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.named('run') {
    standardInput = System.in
}

jar {
    manifest {
        attributes 'Main-Class': 'vermithor.Vermithor'
    }
}
