plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
    id 'checkstyle'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.12.2'
}

javafx {
    version = '25'
    modules = ['javafx.controls']
}

application {
    mainClass = 'vermithor.Launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}

checkstyle {
    toolVersion = '10.26.1'
    configFile = file('config/checkstyle/checkstyle.xml')
}

tasks.named('run') {
    standardInput = System.in
}

jar {
    manifest {
        attributes 'Main-Class': 'vermithor.Launcher'
    }
}

shadowJar {
    archiveBaseName = 'vermithor'
    archiveClassifier = ''
    manifest {
        attributes 'Main-Class': 'vermithor.Launcher'
    }
}
